name: kendamanomics_mobile
description: App used by kendama players to track their progress.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+8

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.1
  provider: ^6.0.5
  kiwi: ^4.1.0
  easy_localization: ^3.0.3
  logger: ^2.0.2+1
  shared_preferences: ^2.2.0
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.16
  uuid: ^4.0.0
  shimmer: ^3.0.0
  video_player: ^2.7.2
  webview_flutter: ^4.2.4
  url_launcher: ^6.1.14
  tuple: ^2.0.2
  app_group_directory: ^2.0.0
  path_provider: ^2.1.1
  flutter_gif: ^0.0.4
  preload_page_view: ^0.2.0
  flutter_mailer: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/
    - assets/icon/
    - assets/config/
    - assets/gif/
    - assets/statics/
    - assets/release_configs/

  fonts:
    - family: GillSans
      fonts:
        - asset: assets/fonts/GillSans-Light.otf
          weight: 300
        - asset: assets/fonts/GillSans-Medium.otf
          weight: 500
#        - asset: assets/fonts/Quicksand-Bold.ttf
#          weight: 700